name: sleep-most
api-version: 1.13
folia-supported: true
version: ${project.version}
main: me.mrgeneralq.sleepmost.Sleepmost
authors: [MrGeneralQ, HorrendousEntity]
commands:
  sleepmost:
    usage: /sleepmost
    description: open the sleepmost help menu
    aliases: [sm]
softdepend: [PlaceholderAPI, GSit, SuperVanish, PremiumVanish, Essentials]